import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

// 

import { Container } from 'react-bootstrap'
import 'bootstrap/dist/css/bootstrap.min.css';


const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-geist-sans",
  display: "swap",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${montserrat.variable}`}>
          <body>{children}</body>
    </html>
  );
}
